### PR TITLE
403 Forbidden fix

### PR DESCRIPTION
**Pull request by cibrhusk**
A minor change to allow import eggs as it was causing a forbidden error due to no user agent provided

### CODE REVIEW

**Comment by cibrhusk** [comment]
AppVeyor failure seems to be caused at the AppVeyor configuration side

**Comment by isanae** [comment]
Nobody has ever reported this problem before and the user agent looks unusual to me. I'm closing without prejudice.

**Comment by cibrhusk** [comment]
Hi, I've taking the trouble of making a fork with a pull request because I am planning to help out, you are asking for developers to help out are you not? When following your modorganizer-umbrella guide from scratch I ran into this problem I would be very much suprised if others will not when starting from scratch. Just try it,
After a bit of googling I've found it mention that it is a known issue when downloading from gitlab (and github) without presenting a user agent. See for example [here](https://stackoverflow.com/questions/39907742/github-api-is-responding-with-a-403-when-using-requests-request-function) although that is for github.

So I got the 403 error and fixed it by adding a user agent, it can be any user agent off course so I you find it unusual just change it (although its not that unusual, its just very basic and provides very few (fake) details to the web server about your client. 

Closing a request without testing it yourself is really putting off any desire to help out more. Such a small change of which anyone can see it will do more good than harm anyway.

**Comment by LostDragonist** [comment]
We've had several new developers follow the same instructions and no one has run into the issue.  We all do clean builds all the time and have had no issues.  You've had zero contact with the team about the issue and provided almost no details about it.  What details you did provide, no one could reproduce.  

I really hope you can see why such a PR might be rejected.  

If this does actually fix something for you, maybe we can incorporate it with a better user agent.  Though it still doesn't make any sense why you'd be the only one with the issue.

**Comment by LostDragonist** [comment]
And... foot in mouth time.  I just did *another* clean build and got the error.  Hooray.  

I wonder when that changed.

**Comment by Holt59** [comment]
This might also be related to the whole AppVeyor failures we have had for weeks. But this does not happen with `mob`, so @isanae can probably tell the differences between both.

**Comment by Al12rs** [comment]
@cibrhusk if you have issues like this or if in general you would like to contribute to Mo2 I invite you to join the MO2 development discord server: https://discord.gg/6GKR9jZ where we discuss changes and issues and where new devs can get introduced to Mo2. There is a #dev-questions channel dedicated to new developers looking to contribute. (And we really could do with some help 😅).

**Comment by cibrhusk** [comment]
@Al12rs et al, I'm glad it turns out to be reproducible, its really annoying when something as trivial as two lines of code is only needed for just the one person, makes me question whats wrong with me ;-)
I'm definitely having more issues as a new developer so I'm sure to come into your discord sooner or later. My background however is not with visual studio but with intellij and with eclipse before that and I've found myself really really lost in visual studio so I'm going to give myself some time do adjust before coming in with the to much noob questions ;-)

**Comment by Al12rs** [comment]
I was worse off when I started. In any case if you wish to contribute or even just follow what we are up to you should join the discord.

**Comment by cibrhusk** [comment]
I don't know why but for some reason I've always had a bit of a reservation before joining a channel like on irc or discord. Coming in feels to me like a promise of commitment and thus I want to be sure of that commitment before hand. A bit of personal reservation I guess.
I understand that a pull request from a complete stranger is not something you take lightly but I thought to myself that two lines of code could speak for itself as I expected the review of it to be trivial.
Anyway, I'll be sure to join your discord when I'm ready to continue.

**Comment by Al12rs** [comment]
There are 8000+ people on discord between testers of devbuilds and users that are there to report issues. Nothing is expected from anyone since this is all for free.
I personally try to stay away from umbrella stuff. We have actually been gradually moving to a new build system developed by isa. If you had showed up on discord we would probably have told you to try that one instead as it's much faster. I have been leaving appveyor and umbrella like they are because we will probably just move to the new build system.
This is the kind of stuff you want to be on the server to know about.

**Comment by LostDragonist** [comment]
Closing this as it's been manually merged with appropriate changes.  Thanks cibrhusk.

**Pull request closed without merging**
