### PR TITLE
Add OMOD installer (WIP)

### PR DESCRIPTION
**Pull request by AnyOldName3**
Remember that this requires CMake 3.18 and also needs to be built with Visual Studio or msbuild -t:restore needs to be run or the nuget packages won't be fetched.

### CODE REVIEW

**Comment by isanae** [comment]
On hold for 2.3.

**Comment by isanae** [comment]
This PR has conflicts.

**Comment by AnyOldName3** [comment]
It also pulls it in from my repo rather than the ModOrganizer2 version, and makes unimake fail until you do an extra manual step, so there are a few ways that this isn't ready for merging yet.

**Comment by AnyOldName3** [comment]
Superceeded by #82

**Pull request closed without merging**
