### PR TITLE
updated Licenses

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by AnyOldName3** [comment]
This might be too many licences (as I have a strong suspicion that a lot of these will be the same and that we aren't obligated to list the licences of all of the dependencies of our dependencies) and some of the names aren't necessarily super clear or consistent (e.g. you've got the LGPL3 called `GNU-LGPL.txt` but the non-L version is called `gpl-3.0.txt`). 

You've also included the PDF manual for command-line ZLib, which does include the ZLib licence, but even if you're including a file which contains the licence rather than just the licence itself (which is readily available all over the internet) surely the readme would have been a better option.

Also, you might want to modify this file: https://github.com/Modorganizer2/modorganizer/blob/Develop/src/aboutdialog.cpp to make the licences get displayed.

**Comment by SuperSandro2000** [comment]
@Silarn will modify https://github.com/Modorganizer2/modorganizer/blob/Develop/src/aboutdialog.cpp

**Comment by Silarn** [comment]
It is true that the dependencies-of-dependencies are probably not required. Castle was something used directly for NCC for instance while ANTLR is a NMM dependency.

We do use CPPTOML as part of lootcli - not just a loot-api dependency.

We can do a deeper review at some point but I'm okay with being too broad for the time being.

**Comment by AnyOldName3** [comment]
A reasonable rule of thumb is that if our dependencies don't include it with their binary releases, either we don't need to include that licence or one of our dependencies is illegally using a library and we're screwed anyway.

**Pull request merged**
